#cloud-config
users:
  - name: concourseci
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4+oMw/XZSNGsCJZHfK3rKIYETpaBOivmSZoVRHAMIzkLpbhlfJpYQ1rxJfYFZakBqoSmKN4MpMF2lDVUz1OcWJOWCUwX3d1nK/0IJB1+ynIA4pF4rm+p2WvNzDXxIJcxhsQpDMJsD6VE0mMm9dLA1gbBQ54rFKBqQA2SxNWrLTSTWKXu3OmEMbV8DsCO89PDmSBjg3tMZai7VXbp2HKjAxQUWU9B4AhJ6JVoyMYFU3K/leV9T9D0s1RITFLuVhcXPQhbayrPHtLt3zK0ZsDkHMigDuMCCMWCzvSL/0JCQBgpI4wUc5X+SEfGuY/oOOpHuh48sRZjGbvIeSEye77Dj
    sudo:  ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    home: /home/concourseci
    groups: wheel

write_files:
  - content: |
      #!/bin/bash
      KEY=uuid
      INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
      REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | awk -F\" '{print $4}')
      TAG_VALUE=$(aws ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=$KEY" --region=$REGION --output=text | cut -f5)
      if [ "${TAG_VALUE}" != "Default"  ] || [ "${TAG_VALUE}" != "" ] ; then
        mkdir -p /opt/apigee/data/edge-message-processor/${TAG_VALUE}
        chown apigee:apigee -R /opt/apigee/data
      fi
    path: /opt/AutoScaling/uuid_configure.sh
    permissions: '0755'

runcmd:
  - sudo /opt/AutoScaling/uuid_configure.sh